version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - {%(name)s:%(lineno)d} - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/geoService-debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: /tmp/geoService-info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: /tmp/geoService-error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: DEBUG
        handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
